import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

import { Navigation } from "../components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-full">
      
      <body className="p-24 max-w-3xl mx-0 my-auto text-gray-50 bg-gradient-to-tr from-black to-neutral-800">
        <Navigation/>
        <div >
          {children}
        </div>
        
      </body>
    </html>
  );
}
